### ISSUE TITLE
Assoziativität in Polynom Operationen

### ISSUE THREAD

**Issue by Eriiiiiiiiiic** [Feeeeeeeeeelix/WolframBeta#10]
Bei Polynomen habe ich mit z.B. __add__ und __mul__ die Operation definiert, aber Python weiß nicht, dass dies sogar assoziativ ist.
Deshalb löst es ein Error aus, wenn ich P+Q+R schreibe.

**Comment by Feeeeeeeeeelix** [comment]
doch haha
