### ISSUE TITLE
Argumente in unterlisten oder selbe ebene als operator?

### ISSUE THREAD

**Issue by Feeeeeeeeeelix** [Feeeeeeeeeelix/WolframBeta#9]
Können wir uns darauf einigen, dass wir in der Baumdarstellung die arguments in eine zweite unterliste tun statt sie in der selben ebene als die funktion/operator lassen:
so: ["*", [a, b, c]]
statt so: ["*", a, b, c]
Es ist zwar nicht leserlicher, aber ich finde es einfacher so zu schreiben und so lesen zu lasse
Und das würden wir für alle operatioenne und funktionen so machen, dass die arguments in eine Unterliste kommen
(Falls es nur ein arg gibt, schreibe ich zb ["sin",  var])
(BTW, ich schreibe nie "x", immer var, damit wir auhc nach einer anderen variabel ableiten können)

**Comment by Feeeeeeeeeelix** [comment]
github hat das "*" zeichen als kursiv befehl interpretiert, die op war multiplication

**Comment by Eriiiiiiiiiic** [comment]
Wie in irl besprochen, wir werden ["+", [a,b,c]] schreiben (ähnlich für alle anderen Operatoren * / - (außer Funktionen))
P.S.: mit "-" vllt machen wir es ja vllt etwas anders, mal sehen...
